---
branches:
  - stable
  - experimental
  - PM4
pulls: false
projects:
  BedcoreProtect:
    path: ""
    icon: resources/bedcoreprotect_logo.png
    libs:
      - src: poggit/libasynql/libasynql
        version: ~4.1.0
      - src: SOF3/await-generator/await-generator
        version: ~3.1.0
      - src: ifera-mc/UpdateNotifier/UpdateNotifier
        version: ~3.0.0
      - src: dktapps-pm-pl/pmforms/pmforms
        version: ~2.1.0
...
