projects:
  BedcoreProtect:
    path: ""
    icon: resources/bedcoreprotect_logo.png
    libs:
      - src: poggit/libasynql/libasynql
        version: 3.2.0
      - src: JackMD/UpdateNotifier/UpdateNotifier
        version: 1.0.0
      - src: matcracker/FormLib/FormLib
        version: 1.1.0
      - src: SOF3/await-generator/await-generator
        version: 2.2.0
...
