---
branches:
  - stable
  - experimental
  - PM4
pulls: false
projects:
  BedcoreProtect:
    path: ""
    icon: resources/bedcoreprotect_logo.png
    libs:
      - src: poggit/libasynql/libasynql
        version: ~3.4.0
        branch: 4.0
      - src: SOF3/await-generator/await-generator
        version: ~3.1.0
      - src: ifera-mc/UpdateNotifier/UpdateNotifier
        version: ~2.2.0
        branch: API-4.0.0
      - src: dktapps-pm-pl/pmforms/pmforms
        version: ~1.0.0
...
