name: BedcoreProtect
main: matcracker\BedcoreProtect\Main
version: 0.5.0
api: [3.4.0]
mcpe-protcol:
  - 354
  - 361

softdepend: BlockSniper
load: POSTWORLD
author: matcracker
description: "BedcoreProtect is a fast, efficient, data logging and anti-griefing tool for PocketMine server. Rollback and restore any amount of damage"
website: https://github.com/matcracker/BedcoreProtect
permissions:
  bcp.command.bedcoreprotect:
    description: "Allows the user to run the command and sub-commands /bedcoreprotect"
    default: op
    children:
      bcp.subcommand.help:
        description: "Allows the user to run the sub-command /bedcoreprotect help"
      bcp.subcommand.reload:
        description: "Allows the user to run the sub-command /bedcoreprotect reload"
      bcp.subcommand.status:
        description: "Allows the user to run the sub-command /bedcoreprotect status"
      bcp.subcommand.inspect:
        description: "Allows the user to run the sub-command /bedcoreprotect inspect"
      bcp.subcommand.near:
        description: "Allows the user to run the sub-command /bedcoreprotect near"
      bcp.subcommand.lookup:
        description: "Allows the user to run the sub-command /bedcoreprotect lookup"
      bcp.subcommand.rollback:
        description: "Allows the user to run the sub-command /bedcoreprotect rollback"
      bcp.subcommand.restore:
        description: "Allows the user to run the sub-command /bedcoreprotect restore"
      bcp.subcommand.purge:
        description: "Allows the user to run the sub-command /bedcoreprotect purge"
      bcp.subcommand.menu:
        description: "Allows the user to run the sub-command /bedcoreprotect menu"